### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by SilentJarl7008** [CodeMouse92/no-monster-minecraft#1]
The command you have listed to remove a certain criteria of mobs, for me at least, is not working

/data modify remove no-monster:rules (mob_category_here) is the command in question

After looking through the game files, I failed to find any information on the command

As well, when I put the command into the game, it fails at "remove" part, as it doesn't recognize it as a possibility

Thanks for taking the time to read this, if you have any questions about it, or need a picture, let me know!

**Comment by CodeMouse92** [comment]
Oops! Good catch, the command is *supposed* to be as follows:

```
/data remove storage no-monster:rules (mob_category_here)
```

Thanks for catching that! I've updated the `README.md`.
