### ISSUE TITLE
Datapack does not install

### ISSUE THREAD

**Issue by JohnnyMasuku** [CodeMouse92/no-monster-minecraft#14]
I'm sorry about that, it's probably something stupid that I don't know how to do. I have a modpack of the Cobblemon mod and I needed to remove the spawns of vanilla mobs for better immersion, I was using the mod "You shall not spawn" to do this, and then I found this modpack of yours and the other "the missing recipes" for being able to craft items without needing mobs. I put the ".zip" file in the "datapack" folder on my server but it doesn't seem to work, I tried putting the files in the "root" part of the zip (I don't know how to explain it), and it didn't work, I tried putting the folder directly without being ".zip" and it didn't work, so I tried a new singleplayer world and installing the datapack at creation, but when I put the datapack in the folder it simply doesn't appear in minecraft, but when I place other datapacks they appear. So what am I doing wrong? Could you help me? I'm sorry if it's something stupid and forgive me for any English mistakes.

**Comment by CodeMouse92** [comment]
It's world specific. You should extract the .zip files, and then put the resulting folders into `saves/<your world>/datapacks/`.

**Comment by JohnnyMasuku** [comment]
Thank you very much, I knew it was something stupid

**Comment by CodeMouse92** [comment]
Not stupid, just not obvious.
