### ISSUE TITLE
Version for 1.21

### ISSUE THREAD

**Issue by trainphreak** [CodeMouse92/no-monster-minecraft#15]
Per [the 1.21 announcement post](https://www.minecraft.net/en-us/article/minecraft-java-edition-1-21#:%7E:text=TAGS-,DIRECTORY%20RENAMES,-Some%20registry%20types:~:text=TAGS-,DIRECTORY%20RENAMES,-Some%20registry%20types), several Minecraft registry folders have been renamed to be singular instead of plural. As a result, when this pack is loaded on 1.21 and higher, it fails to register most of its functionality.

Fortunately, the fix is trivial: rename all the folders listed in the announcement post.

**Comment by CodeMouse92** [comment]
Yeah, I need to create the version of this for 1.21, as there are also the new mobs to content with.

**Comment by CodeMouse92** [comment]
This is addressed in today's release.
