### ISSUE TITLE
How do i enable hostile mobs. or are they already enabled 

### ISSUE THREAD

**Issue by MinePROS19** [CodeMouse92/no-monster-minecraft#3]
How do i enable hostile mobs. or are they already enabled

**Comment by MinePROS19** [comment]
and plz leave a vid on how to do it if u can

**Comment by MinePROS19** [comment]
btw good job

**Comment by CodeMouse92** [comment]
You have to determine which hostile mobs you want. They're divided into groups: see https://github.com/codemouse92/no-monster-minecraft#mob-control

To enable a group, run the following command, substituting the correct rule (from that documentation above) in for `spawnIllagers`:

```
/data modify storage no-monster:rules spawnIllagers set value true
```

If you enable the wrong group, you can disable it again with...

```
/data remove storage no-monster:rules spawnIllagers
```

I won't have time to do a video — extraordinarily busy — but if I had, it would be nothing more than showing those above commands anyway.

**Comment by MinePROS19** [comment]
thank you code mouse you have done something i have been looking for the past 5 years. Good job

**Comment by CodeMouse92** [comment]
Yay! :D
