### ISSUE TITLE
I hear teleporting sounds when it's raining

### ISSUE THREAD

**Issue by vinnyg0621** [CodeMouse92/no-monster-minecraft#5]
Idk why, but I keep hearing teleporting sounds when it rains. could someone please fix this?

**Comment by embeddedt** [comment]
That's probably endermen teleporting. I'm not sure if the datapack can fix this because I think it removes mobs on the tick after they spawn.

**Comment by CodeMouse92** [comment]
Exactly right, @embeddedt!

Basically, the datapack teleports all targeted mobs to well below the world (negative Y), where they are killed by the void. This prevents mob-drop clutter from removed targeted mobs, without eliminating mob drops for all the mobs you actually want around.

The function to perform this teleportation happens every game tick. As a result, you will see "flickering" of mobs on the landscape at night, and occasionally hear endermen teleportation during rainstorms. There's really no way to fix either of those issues with a datapack at this time.

If you really don't want to hear it anymore, and play with _all_ hostile mobs suppressed, you may consider turning off Hostile Mob Sounds in the settings.

**Comment by embeddedt** [comment]
Another workaround if you only need to fight the wither/ender dragon is to play on peaceful mode and add a mod which re-enables hunger.

**Comment by CodeMouse92** [comment]
@embeddedt Just bear in mind, peaceful mode will also eliminate all danger from non-monster mobs, e.g. bees, wolves, polar bears, and the like. NMMC leaves those mobs alone, to keep some of the challenge.

**Comment by CodeMouse92** [comment]
@vinnyg0621 We've reworked how mobs despawn, and that will probably resolve this. I'm changing the status to "Resolved", but if you have the problem reoccur, please reopen the issue. Thanks!

**Comment by CodeMouse92** [comment]
(Should be resolved.)
